### ISSUE TITLE
error on install with latest node.

### ISSUE THREAD

**Issue by klh** [hsfeng/generator-amdblah#1]
npm ERR! tar.unpack untar error /Volumes/SlowMo/Users/kk/.npm/tar/0.1.19/package.tgz
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/generator-amdblah/node_modules/yeoman-generator/node_modules/tar/lib/header.js'

**Comment by hsfeng** [comment]
Now you can run amdblah on the latest version( v4.0.0) of Node.js. thanks
